In [43]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.svm import SVC
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [ ]:
review_train = pd.read_csv("yelp_academic_dataset_review_train.csv")
vectorizer = CountVectorizer(min_df=0.003, stop_words='english')
X = vectorizer.fit_transform(review_train['text'])
y = review_train['stars']

Logistic regression

In [6]:
logistic_model = LogisticRegression(max_iter=1e3)

In [7]:
scores_logistic = cross_val_score(logistic_model, X, y, cv=5)

In [8]:
scores_logistic

array([ 0.58290767,  0.58941449,  0.58368749,  0.58038896,  0.58498261])

SVM Model

In [10]:
svm_model = SVC(C=.1, max_iter=1e2)

In [11]:
scores_svm = cross_val_score(svm_model, X, y, cv=5)

/usr/local/lib/python3.5/site-packages/sklearn/svm/base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.5/site-packages/sklearn/svm/base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.5/site-packages/sklearn/svm/base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.5/site-packages/sklearn/svm/base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.5/site-packages/sklearn/svm/base.py:2

In [63]:
svm_model.support_vectors_

<1378x1285 sparse matrix of type '<class 'numpy.float64'>'
	with 9121 stored elements in Compressed Sparse Row format>

In [12]:
scores_svm

array([ 0.35450916,  0.35332246,  0.35235029,  0.3532821 ,  0.35306745])

Trying different vectorizer

In [38]:
vectorizer2 = CountVectorizer(min_df=0.005, stop_words='english')
X = vectorizer2.fit_transform(review_train['text'])

In [39]:
logistic_model = LogisticRegression(max_iter=1e3)
scores_logistic = cross_val_score(logistic_model, X, y, cv=5)
scores_logistic

array([ 0.57960252,  0.5872682 ,  0.58218502,  0.57910102,  0.58356588])

In [24]:
scores_logistic

array([ 0.58213504,  0.59417926,  0.58450311,  0.58107586,  0.58468209])

In [20]:
X

<116474x1787 sparse matrix of type '<class 'numpy.int64'>'
	with 3636771 stored elements in Compressed Sparse Row format>

LDA Model

In [44]:
lda_model = LinearDiscriminantAnalysis()

In [46]:
scores_lda = cross_val_score(logistic_model, X.toarray(), y, cv=5)
scores_lda

array([ 0.57960252,  0.5872682 ,  0.58218502,  0.57910102,  0.58356588])

In [67]:
lda_model.fit(X.toarray(), y)

LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)

In [71]:
lda_model.priors_

array([ 0.13827979,  0.10448684,  0.13546371,  0.27047238,  0.35129729])